server:
  port: 7010

spring:
  application:
    name: zipkinClient
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 0.5
  sample:
    zipkin:
      enabled: true